name       : perl-sub-quote
version    : '2.006006'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Sub-Quote-2.006006.tar.gz : 6e4e2af42388fa6d2609e0e82417de7cc6be47223f576592c656c73c7524d89d
homepage   : https://metacpan.org/pod/Sub::Quote
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Sub::Quote - Efficient generation of subroutines via string eval
description: |
    This package provides performant ways to generate subroutines from strings.
builddeps  :
    - perl-sub-name
    - perl-test-fatal
rundeps    :
    - perl-sub-name
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
