name       : perl-sub-quote
version    : '2.006008'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Sub-Quote-2.006008.tar.gz : 94bebd500af55762e83ea2f2bc594d87af828072370c7110c60c238a800d15b2
homepage   : https://metacpan.org/pod/Sub::Quote
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Sub::Quote - Efficient generation of subroutines via string eval
description: |
    This package provides performant ways to generate subroutines from strings.
builddeps  :
    - perl-sub-name
    - perl-test-fatal
rundeps    :
    - perl-sub-name
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
