name       : perl-sub-quote
version    : 2.005001
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Sub-Quote-2.005001.tar.gz : d6ab4f0775def015367a05e02024b403f991b2be11d774f3d235fe7e9bdbba07
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Sub::Quote - Efficient generation of subroutines via string eval
description: |
    This package provides performant ways to generate subroutines from
    strings.
builddeps  :
    - perl-sub-name
    - perl-test-fatal
rundeps    :
    - perl-sub-name
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
